#Made by BGHDDevelopment(Noodles)
#=======================================================
Messages:
  PumpkinHeadMessage: '&b&lHappy Halloween! &6&lEnjoy a pumpkin!'
  PublicLightningMessage: '&b&lHappy Halloween! &6&lHave LIGHTNING!'
  PrivateLightningMessage: '&7Hit all players with lightning! (no damage)'
  PumpkinHeadAllPlayersMessage: '&6&lEnjoy halloween with a pumpkin!'
  BatSwarmMessage: '&8&lBATS!'
  
#Commands & Permissions
#/pumpkinhead - halloween.pumpkinhead
#/lightning - halloween.lightning
#/pumkinheadall - halloween.pumpkinheadall
#/batswarm - halloween.batswarm
#/scare - halloween.scare