main: me.noodles.halloween.Main
name: HalloweenUtilities
version: 0.4
author: BGHDDevelopment
commands:
  pumpkinhead:
    description: Put a pumpkin on your head!
  lightning:
    description: Haunt players with lightning!
  pumpkinheadall:
    description: Put a pumpkin on all players heads!
  batswarm:
    description: Spawn a swarm of bats on every player!
  halloween:
    description: Halloween plugin info!
  scare:
    description: Scare Players!